### ISSUE TITLE
Fish going out of bounds

### ISSUE THREAD

**Issue by diarmuidtherat** [Haydoggo/Beach-Escape#15]
If a fish with a path that moves diagonally is selected, they will move out of bounds if placed in certain locations (the top for the seahorse, and the bottom for the crab respectively), or if a tower/rock changes their pathing such that they move there. This could be a legitimate strategy for some levels, however in its current state it looks more like a bug than anything else. An easy solution to this is to give the background a subtle tile texture, or making it so the area outside of the play area are effectively "rocks".

**Comment by Haydoggo** [comment]
Closed by bf6d7562fded8d6fba44b4d89f0aac4ae5ce4785
