### ISSUE TITLE
Unit/tower description sometimes doesn't go away

### ISSUE THREAD

**Issue by Haydoggo** [Haydoggo/Beach-Escape#16]
The description window often stays visible and gets in the way of larger levels.

**Comment by plexsoup** [comment]
seems to happen when two towers are adjacent, and user mouse-overs both of them quickly.
Probably getting an open command after a close command, then failing to close subsequently? Likely a State change missing somewhere.

**Comment by plexsoup** [comment]
I've resized the hover-area on towers, so they shouldn't overlap. (96px instead of 128)
