### ISSUE TITLE
reward alternate strategies to prevent a single conga line

### ISSUE THREAD

**Issue by plexsoup** [Haydoggo/Beach-Escape#19]
With static defences, there's a clear dominant strategy: send all units down one cleared lane.
All players will do this because they like to win, but they'll feel unsatisfied because it seems cheap.

Find rewards for using multiple lanes or disincentivize the single conga line strategy.

**Comment by plexsoup** [comment]
A few possible options:

- have towers move one square, randomly, every 10 ticks.
- have the fishing hook reappear on entirely new tiles every 5 ticks or so.
- consider a press-your luck mechanic where too many fish in one lane increases the probability of a big monster coming.
- consider benefits to coordinating movement in multiple lanes: like a boon which affects all units in a single column.

**Comment by plexsoup** [comment]
one of our fish should move diagonally

**Comment by Haydoggo** [comment]
Utilise fish/towers that move fish. Have many rocks in the way to make navigation require lane shifts

**Comment by Haydoggo** [comment]
Have seagulls act as a sort of taxi service? Get a fish to each perch to have the seagull swap them?

**Comment by plexsoup** [comment]
arcade levels allow towers to move once every 10 ticks
