### ISSUE TITLE
Fix the Pelican

### ISSUE THREAD

**Issue by diarmuidtherat** [Haydoggo/Beach-Escape#26]
Pelican should:

1. damage a fish that is inside it, every tick
2. be damaged by the fish that is inside it, every tick
3. target fish that enter the area around it, not just directly in front of it
4. only try to eat a fish if it is not currently trying to eat a fish

**Comment by plexsoup** [comment]
I've refactored the pelican to 
- if it's not currently eating a fish:
  - test 3 squares around it (Left, Up, Down)
    - grab the first fish not sharing a square with a tower
      - deal damage to the fish
      - take damage from the fish
      - release the fish after 2 beats

**Comment by plexsoup** [comment]
Diarmuid reports the pelican should, but does not: release the captive fish when the pelican dies.

**Comment by plexsoup** [comment]
Hayden reports the pelican is spitting fish out in their original square, but the fish should be spit out in the pelican's square.
