### ISSUE TITLE
Fix baselevel not allowing you to quickload certain units

### ISSUE THREAD

**Issue by diarmuidtherat** [Haydoggo/Beach-Escape#27]
Namely the octopus, seahorse, and sad fish.

**Comment by plexsoup** [comment]
honestly I have no idea what causes this. You might have to drag units onto the resource from the file manager instead of using quickload.
<img width="357" alt="image" src="https://github.com/Haydoggo/Beach-Escape/assets/8674767/ac8379b8-d094-481a-a1cc-6919b65b532c">
