### ISSUE TITLE
button toggled focus ring doesn't update, when next available unit is auto-selected

### ISSUE THREAD

**Issue by plexsoup** [Haydoggo/Beach-Escape#35]
The game, in BaseLevel.gd select_first_available_button(), auto-selects the next available unit in two situations:
- at the very start
- whenever a player empties their supply of any particular type of fish.

The problem I'm having is that the button Focus Line2D doesn't update when the game auto-selects a new unit.

**Comment by Haydoggo** [comment]
fixed by db6200e8755a7f944eb8b074b02332b1e1a90dbc
