### ISSUE TITLE
Fix the Tack Shooter

### ISSUE THREAD

**Issue by diarmuidtherat** [Haydoggo/Beach-Escape#36]
1. it continues shooting after its target has died
2. the hitbox it shoots remains active until a fish passes through them, which is why "1" is even a problem; the tack shooter can stack as many hitboxes around itself as it continues shooting, often instakilling the next fish that gets close.

**Comment by plexsoup** [comment]
I've added duration_in_ticks to "projectiles", so they shouldn't hang around longer than needed.
The "projectile" on the tack shooter has no velocity, so it just sits there, but with the new duration of 1 tick, it should go away.
Hopefully that fixes the damage stacking problem.

I couldn't verify that it continues shooting after the target is dead. Still testing.
