### ISSUE TITLE
sometimes puffer fish gets stuck in grass

### ISSUE THREAD

**Issue by plexsoup** [Haydoggo/Beach-Escape#41]
<img width="172" alt="image" src="https://github.com/Haydoggo/Beach-Escape/assets/8674767/f81fc774-ca67-4ade-b22c-0d78389b4971">

I was playing through the arcade mode and got a puffer fish hung up on the grass, unable to move.

**Comment by plexsoup** [comment]
maybe got fixed when a similar octopus bug was resolved?
I haven't seen this bug lately.

**Comment by Haydoggo** [comment]
Might happen if the grass deals any damage?
