### ISSUE TITLE
New Towers and Obstacles

### ISSUE THREAD

**Issue by diarmuidtherat** [Haydoggo/Beach-Escape#6]
- [x] Pelican: Large bird that sits in one place. Any fish that gets within 1 (2?) tile of it is immediately taken into its beak (but only one at a time), and each tick, the Pelican will deal some damage to the fish. If the fish deals enough damage, the Pelican will spit the fish out on the other side, but if the fish dies first, the Pelican consumes it.

- [ ] Squid: Blasts ink at nearby fish, slowing them down.

- [x] Fish Hook: If a fish walks through a tile with a fish hook on it, they will take damage per tick until they die or make it out.

- [x] Seagrass: Any fish that walks through a tile with seagrass on it will be slowed while inside it (take an extra tick to move out of it).

**Comment by plexsoup** [comment]
all towers implemented except squid
