### ISSUE TITLE
Sand Projectile Hit Gets Cut Off

### ISSUE THREAD

**Issue by RonnocJ** [Haydoggo/Beach-Escape#8]
It only happens sometimes, I previewed the sounds to make sure they exported correctly, but when I ran the ExampleScene it sounded like about 1/3 of the time the sound gets cut off after the projectile hits. Not a super urgent issue because especially after the music gets added it won't be too noticeable.

**Comment by plexsoup** [comment]
I changed the duration of the sand projectile explode animation to 1.3. Hopefully that resolves the issue.
